# Generated by Django 4.2.1 on 2023-06-04 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vegetable", "0003_receipe_receipeviewcount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["department"],
            },
        ),
        migrations.CreateModel(
            name="StudentID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("studentId", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("studentName", models.CharField(max_length=100)),
                ("studentEmail", models.EmailField(max_length=254, unique=True)),
                ("studentAge", models.IntegerField(default=1)),
                ("studentAddress", models.TextField()),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depart",
                        to="vegetable.department",
                    ),
                ),
                (
                    "studentId",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studentid",
                        to="vegetable.studentid",
                    ),
                ),
            ],
            options={
                "verbose_name": "student",
                "ordering": ["studentName"],
            },
        ),
    ]
