# Generated by Django 4.2.1 on 2023-06-06 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vegetable", "0005_subject_subjectmarks"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateOfReportCardGeneration", models.DateField(auto_created=True)),
                ("studentMark", models.IntegerField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studentreportcard",
                        to="vegetable.student",
                    ),
                ),
            ],
        ),
    ]
