# Generated by Django 4.2.1 on 2023-06-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vegetable", "0006_reportcard"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reportcard",
            old_name="studentMark",
            new_name="studentRank",
        ),
        migrations.AlterUniqueTogether(
            name="reportcard",
            unique_together={("studentRank", "dateOfReportCardGeneration")},
        ),
    ]
