# Generated by Django 4.2.1 on 2023-06-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vegetable", "0007_rename_studentmark_reportcard_studentrank_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportcard",
            name="dateOfReportCardGeneration",
            field=models.DateField(auto_now_add=True),
        ),
    ]
