# Generated by Django 4.2.1 on 2023-06-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vegetable", "0008_alter_reportcard_dateofreportcardgeneration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipe",
            name="user",
        ),
    ]
