# Generated by Django 4.2.1 on 2023-06-07 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vegetable", "0009_remove_receipe_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipe",
            name="isDeleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="receipe",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
