# Generated by Django 4.2.1 on 2023-06-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vegetable", "0010_receipe_isdeleted_receipe_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipe",
            name="isDeleted",
        ),
        migrations.AddField(
            model_name="student",
            name="isDeleted",
            field=models.BooleanField(default=False),
        ),
    ]
