# Generated by Django 4.2.1 on 2023-06-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_student_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carName", models.CharField(max_length=100)),
                ("speed", models.IntegerField(default=50)),
            ],
        ),
    ]
